- name: Provisioning MariaDB Server
  hosts: db01
  tasks:
    - name: Import Variables
      include_vars: vars/stack_setup_vars

    - name: Update patches and Install Required packages for MariaDB Server.
      shell: |
        sudo yum update -y 
        sudo yum install epel-release -y
        sudo yum install git zip unzip -y
        sudo yum install mariadb-server -y
 
    - name: Start and enabling MariaDB server
      shell: |
        sudo systemctl start mariadb
        sudo systemctl enable mariadb
    
    - name: Cloning Repo
      shell: |
        cd /tmp/
        git clone -b local-setup https://github.com/devopshydclub/vprofile-project.git

    - name: Restore the dump file from the Application
      shell: |
        sudo mysqladmin -u root password "{{DATABASE_PASS}}"
        sudo mysql -u root -p"{{DATABASE_PASS}}" -e "UPDATE mysql.user SET Password=PASSWORD('{{DATABASE_PASS}}') WHERE User='root'"
        sudo mysql -u root -p"{{DATABASE_PASS}}" -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
        sudo mysql -u root -p"{{DATABASE_PASS}}" -e "DELETE FROM mysql.user WHERE User=''"
        sudo mysql -u root -p"{{DATABASE_PASS}}" -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
        sudo mysql -u root -p"{{DATABASE_PASS}}" -e "FLUSH PRIVILEGES"
        sudo mysql -u root -p"{{DATABASE_PASS}}" -e "create database accounts"
        sudo mysql -u root -p"{{DATABASE_PASS}}" -e "grant all privileges on accounts.* TO 'admin'@'localhost' identified by 'admin123'"
        sudo mysql -u root -p"{{DATABASE_PASS}}" -e "grant all privileges on accounts.* TO 'admin'@'%' identified by 'admin123'"
        sudo mysql -u root -p"{{DATABASE_PASS}}" accounts < /tmp/vprofile-project/src/main/resources/db_backup.sql
        sudo mysql -u root -p"{{DATABASE_PASS}}" -e "FLUSH PRIVILEGES"

    - name: Restarting MariaDB
      command: 'sudo systemctl restart mariadb'



