- name: Provisioning Tomcat Server
  hosts: app01
  tasks:
    - name: Import Variables
      include_vars: vars/stack_setup_vars

    - name: Update patches and Install Required packages for TOMCAT Server
      become: yes
      become_user: root
      shell: |
        sudo yum update -y 
        sudo yum install epel-release -y
        sudo yum install git zip unzip -y      
        sudo yum install java-1.8.0-openjdk -y
        sudo yum install git maven wget -y
        
    - name: Download and untar tomcat pakacges
      become: yes
      become_user: root
      shell: |
        cd /tmp
        sudo wget {{TOMURL}} -O tomcatbin.tar.gz
        sudo tar xzvf tomcatbin.tar.gz

    - name: Adding user tomcat to the system
      become: yes
      become_user: root    
      shell: |    
        sudo useradd --shell /sbin/nologin tomcat

    - name: Sync from /tmp/apache-tomcat* /usr/local/tomcat8/
      become: yes
      become_user: root
      shell: |
        sudo rsync -avzh /tmp/apache-tomcat-8.5.37/ /usr/local/tomcat8/
        sudo chown -R tomcat.tomcat /usr/local/tomcat8        
    
    - name: Create a tomcat.service
      become: yes
      become_user: root
      shell: |    
        cat << EOF > /etc/systemd/system/tomcat.service
        [Unit]
        Description=Tomcat
        After=network.target   

        [Service]

        User=tomcat
        Group=tomcat        

        WorkingDirectory=/usr/local/tomcat8

        #Environment=JRE_HOME=/usr/lib/jvm/jre
        Environment=JAVA_HOME=/usr/lib/jvm/jre        

        Environment=CATALINA_PID=/var/tomcat/%i/run/tomcat.pid
        Environment=CATALINA_HOME=/usr/local/tomcat8
        Environment=CATALINE_BASE=/usr/local/tomcat8        

        ExecStart=/usr/local/tomcat8/bin/catalina.sh run
        ExecStop=/usr/local/tomcat8/bin/shutdown.sh
        
        RestartSec=10
        Restart=always 

        [Install]
        WantedBy=multi-user.target
        EOF        
        
    - name: Restart daemon and tomcat service
      become: yes
      become_user: root
      shell: |
        sudo sed -i 's/EOF//g' /etc/systemd/system/tomcat.service
        sudo chown tomcat.tomcat /etc/systemd/system/tomcat.service
        sudo systemctl daemon-reload
        sudo systemctl start tomcat
        sudo systemctl enable tomcat        

    - name: Cloning repo
      become: yes
      become_user: root
      shell: |    
        sudo git clone -b local-setup https://github.com/devopshydclub/vprofile-project.git
        
        
    - name: Building MVN 
      become: yes
      become_user: root
      shell: |    
        cd vprofile-project
        sudo mvn install

    - name: Stopping tomcat service 
      become: yes
      become_user: root
      shell: |
        sudo systemctl stop tomcat; sleep 60
        
    - name: Removing Defauklt ROOT web directory 
      become: yes
      become_user: root
      shell: |
        cd vprofile-project     
        sudo rm -rf /usr/local/tomcat8/webapps/ROOT*
        sudo cp target/vprofile-v2.war /usr/local/tomcat8/webapps/ROOT.war

    - name: Starting tomcat service ; sleeping for 120 seconds
      become: yes
      become_user: root
      shell: |    
        sudo systemctl start tomcat; sleep 120
                
    - name: Restarting tomcat service    
      become: yes
      become_user: root
      shell: |
        sudo systemctl restart tomcat